package sayfalar;

import Kullanicilar.doktor;
import Kullanicilar.hasta;
import arayuz_islemleri.doktor_giris_ekran_islemleri;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sql_islemleri.sql_kullanici_islemleri;

public class doktor_giris extends javax.swing.JFrame {

    //degiskenler - DBIsimleri
    private String DB_Kullanici = "hastane";

    //classlar
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    doktor_giris_ekran_islemleri girisEkran;
    sql_kullanici_islemleri sqlKullaniciİslemleri = new sql_kullanici_islemleri(DB_Kullanici);

    //degiskenler (sonra silinecek, db uzerinden cekilecek)
    /*
    public String TCKN="123";
    public String sifre="123";
     */
    /**
     * Creates new form giris
     */
    public doktor_giris() {
        initComponents();
        
        //ekrani tam ortaya ayarladik
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_DoktorAdi = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel_TCKN = new javax.swing.JLabel();
        jLabel_Sifre = new javax.swing.JLabel();
        jLabel_Image = new javax.swing.JLabel();
        jButton_Giris_Yap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_swipe_mode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(62, 62, 62));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(62, 62, 62));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 800));

        jTextField_DoktorAdi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_DoktorAdi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_DoktorAdi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_DoktorAdi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "Doktor Adı", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jPasswordField.setBackground(new java.awt.Color(62, 62, 62));
        jPasswordField.setForeground(new java.awt.Color(245, 229, 193));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "Şifre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jLabel_TCKN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\user_24x24.png")); // NOI18N

        jLabel_Sifre.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\lock.png")); // NOI18N

        jLabel_Image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\hospital-building.png")); // NOI18N
        jLabel_Image.setText("jLabel1");

        jButton_Giris_Yap.setBackground(new java.awt.Color(244, 114, 43));
        jButton_Giris_Yap.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_Giris_Yap.setForeground(new java.awt.Color(245, 229, 193));
        jButton_Giris_Yap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\login.png")); // NOI18N
        jButton_Giris_Yap.setText("Giriş Yap");
        jButton_Giris_Yap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(62, 62, 62), 3, true));
        jButton_Giris_Yap.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_Giris_Yap.setIconTextGap(15);
        jButton_Giris_Yap.setPreferredSize(new java.awt.Dimension(109, 33));
        jButton_Giris_Yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Giris_YapActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 114, 43));
        jLabel1.setText("Doktor Girişi");

        jButton1_swipe_mode.setBackground(new java.awt.Color(244, 114, 43));
        jButton1_swipe_mode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1_swipe_mode.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\swipe.png")); // NOI18N
        jButton1_swipe_mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_swipe_modeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Sifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_TCKN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_DoktorAdi)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton1_swipe_mode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Giris_Yap, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel_Image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_DoktorAdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TCKN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Sifre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Giris_Yap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_swipe_mode))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButton_Giris_YapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Giris_YapActionPerformed
        // TODO add your handling code here:
        girisEkran = new doktor_giris_ekran_islemleri(jTextField_DoktorAdi, jPasswordField);
        String girilenDoktorAdi = jTextField_DoktorAdi.getText();
        String girilenSifre = new String(jPasswordField.getPassword());
        Boolean girisSonuc = false;
        Boolean sifreSonuc = false;

        doktor kullanici = null;
        //sql_kullanici_islemleri icindeki denenme fonksiyonu burada cagirildi
        try {
            
            girisSonuc=girisEkran.bosGirisKontrol();
            
            if(girisSonuc){
                kullanici=sqlKullaniciİslemleri.doktor_bul(girilenDoktorAdi, girilenSifre);
                if(kullanici==null){
                    throw new NullPointerException();
                }
                else{
                    System.out.println("Kullanici bulundu!");
                    this.setVisible(false); //suanki giris ekrani gorunmez yapilacak
                    anasayfa anasayfaUI= new anasayfa(kullanici);
                    anasayfaUI.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, girisEkran.getSonucMesaj());
            }
            
            //sqlKullaniciİslemleri.deneme();
        } catch (SQLException ex) {
            Logger.getLogger(doktor_giris.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Kullanici bulunamadi :(");
        }
    }//GEN-LAST:event_jButton_Giris_YapActionPerformed

    private void jButton1_swipe_modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_swipe_modeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        hasta_giris hastaUI=new hasta_giris();
        hastaUI.setVisible(true);
    }//GEN-LAST:event_jButton1_swipe_modeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktor_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktor_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktor_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktor_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktor_giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_swipe_mode;
    public javax.swing.JButton jButton_Giris_Yap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Sifre;
    private javax.swing.JLabel jLabel_TCKN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_DoktorAdi;
    // End of variables declaration//GEN-END:variables
}
