package sayfalar;

import UI_Hasta.UI_Doktor;
import UI_Hasta.UI_Hasta;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sql_islemleri.sql_kullanici_islemleri;

/**
 *
 * @author Korac
 */
public class doktor_kayit extends javax.swing.JFrame {
    
    //degiskenler
    private String DB_Kullanici = "hastane";
    public static String isim;
    public static int tckn;
    public static int d_id;
    
    //classlar
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    ImageIcon icon =new ImageIcon("src\\main\\java\\images\\checked.png");
    sql_kullanici_islemleri sqlKullaniciİslemleri = new sql_kullanici_islemleri(DB_Kullanici);
    /**
     * Creates new form hasta_kayit
     */
    public doktor_kayit(String isim,int d_id) {
        initComponents();
         //ekrani tam ortaya ayarladik
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.isim=isim;
        this.d_id=d_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_doktor_adi = new javax.swing.JTextField();
        jTextField_doktor_id = new javax.swing.JTextField();
        jTextField_bolum_ismi = new javax.swing.JTextField();
        jTextField_doktor_soyadi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_restart = new javax.swing.JButton();
        jButton_checked = new javax.swing.JButton();
        jButton_register = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(62, 62, 62));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(62, 62, 62));

        jTextField_doktor_adi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_doktor_adi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_doktor_adi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_doktor_adi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "doktor adı", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jTextField_doktor_id.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_doktor_id.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_doktor_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_doktor_id.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "doktor id", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jTextField_bolum_ismi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_bolum_ismi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_bolum_ismi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_bolum_ismi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "bölüm ismi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jTextField_doktor_soyadi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_doktor_soyadi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_doktor_soyadi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_doktor_soyadi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "doktor soyadı", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 114, 43));
        jLabel1.setText("Doktor Kayit");

        jButton_restart.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\restart.png")); // NOI18N
        jButton_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restartActionPerformed(evt);
            }
        });

        jButton_checked.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\checked.png")); // NOI18N
        jButton_checked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkedActionPerformed(evt);
            }
        });

        jButton_register.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\register.png")); // NOI18N
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        jButton_home.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\home.png")); // NOI18N
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(62, 62, 62));
        jPasswordField.setForeground(new java.awt.Color(245, 229, 193));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "Şifre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_doktor_id, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_doktor_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_doktor_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_bolum_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_restart)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_home)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_register)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_checked))
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jTextField_doktor_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_doktor_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_doktor_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_bolum_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_checked)
                    .addComponent(jButton_home)
                    .addComponent(jButton_register)
                    .addComponent(jButton_restart))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_checkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkedActionPerformed
        // TODO add your handling code here:
        UI_Doktor ui_doktor=new UI_Doktor(
                jTextField_doktor_id,
                jTextField_doktor_adi,
                jTextField_doktor_soyadi,
                jPasswordField,
                jTextField_bolum_ismi
        );
        if(ui_doktor.bos_alan_kontrol_pass())
        {   
            ui_doktor.doktor_tanimla_pass();
            JOptionPane.showMessageDialog(this, "Doktor basariyla kayit edildi :)","Kayit Basarili !",JOptionPane.PLAIN_MESSAGE,icon);
        }
        else{
            JOptionPane.showMessageDialog(this, "Bos alan birakmayiniz !    ", "Uyari!" ,   JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_checkedActionPerformed

    private void jButton_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restartActionPerformed
        this.jTextField_doktor_id.setText("");
        this.jTextField_doktor_adi.setText("");
        this.jTextField_doktor_soyadi.setText("");
        this.jPasswordField.setText("");
        this.jTextField_bolum_ismi.setText("");
    }//GEN-LAST:event_jButton_restartActionPerformed

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
        this.setVisible(false);
        doktor_giris d_giris=new doktor_giris();
        d_giris.setVisible(true);
    }//GEN-LAST:event_jButton_registerActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        this.setVisible(false);
        anasayfa ana_sayfa = null;
        try {
            ana_sayfa = new anasayfa(true,isim,tckn,d_id);
            System.out.println("doktor kayittan yollanan d_id:" +d_id);
        } catch (SQLException ex) {
            Logger.getLogger(doktor_kayit.class.getName()).log(Level.SEVERE, null, ex);
        }
        ana_sayfa.setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktor_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktor_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktor_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktor_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktor_kayit(isim,d_id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_checked;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_register;
    private javax.swing.JButton jButton_restart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_bolum_ismi;
    private javax.swing.JTextField jTextField_doktor_adi;
    private javax.swing.JTextField jTextField_doktor_id;
    private javax.swing.JTextField jTextField_doktor_soyadi;
    // End of variables declaration//GEN-END:variables
}
