package sayfalar;

import UI_Hasta.UI_Hasta;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sql_islemleri.sql_kullanici_islemleri;

/**
 *
 * @author Korac
 */
public class hasta_kayit extends javax.swing.JFrame {

    //degiskenler
    private String DB_Kullanici = "hastane";
    public static String isim; 
    public static int Tckn;
    public String status;

    //classlar
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    ImageIcon icon = new ImageIcon("src\\main\\java\\images\\checked.png");
    sql_kullanici_islemleri sqlKullaniciİslemleri = new sql_kullanici_islemleri(DB_Kullanici);

    public hasta_kayit(String isim,int tckn) {
        initComponents();
        //ekrani tam ortaya ayarladik
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.isim=isim;
        this.Tckn=tckn;
        this.status=isim;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_hasta_tckn = new javax.swing.JTextField();
        jTextField_hasta_adi = new javax.swing.JTextField();
        jTextField_hasta_soyadi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_restart = new javax.swing.JButton();
        jButton_checked = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        jButton_register = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(62, 62, 62));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(62, 62, 62));

        jTextField_hasta_tckn.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_hasta_tckn.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_hasta_tckn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_hasta_tckn.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "hasta tckn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jTextField_hasta_adi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_hasta_adi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_hasta_adi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_hasta_adi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "hasta adı", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jTextField_hasta_soyadi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_hasta_soyadi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_hasta_soyadi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_hasta_soyadi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "hasta soyadi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 114, 43));
        jLabel1.setText("Hasta Kayit");

        jButton_restart.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\restart.png")); // NOI18N
        jButton_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restartActionPerformed(evt);
            }
        });

        jButton_checked.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\checked.png")); // NOI18N
        jButton_checked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkedActionPerformed(evt);
            }
        });

        jButton_home.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\home.png")); // NOI18N
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_register.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\register.png")); // NOI18N
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(62, 62, 62));
        jPasswordField.setForeground(new java.awt.Color(245, 229, 193));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "Şifre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_hasta_tckn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_hasta_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_hasta_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_restart)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_home)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_register)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_checked))
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addComponent(jTextField_hasta_tckn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_hasta_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_hasta_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_checked)
                    .addComponent(jButton_restart)
                    .addComponent(jButton_home)
                    .addComponent(jButton_register))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_checkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkedActionPerformed
        UI_Hasta ui_hasta = new UI_Hasta(
                //null,
                jTextField_hasta_tckn,
                jTextField_hasta_adi,
                jTextField_hasta_soyadi,
                jPasswordField
        );
        
        if (ui_hasta.bos_alan_kontrol_pass()) {
            ui_hasta.hasta_tanimla_pass();
            JOptionPane.showMessageDialog(this, "Hasta basariyla kayit edildi :)", "Kayit Basarili !", JOptionPane.PLAIN_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(this, "Bos alan birakmayiniz !    ", "Uyari!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_checkedActionPerformed

    private void jButton_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restartActionPerformed
        //this.jTextField_hasta_id.setText("");
        this.jTextField_hasta_tckn.setText("");
        this.jTextField_hasta_adi.setText("");
        this.jTextField_hasta_soyadi.setText("");
        this.jPasswordField.setText("");
    }//GEN-LAST:event_jButton_restartActionPerformed
//  private javax.swing.JLabel jLabel_randevu_al;
// jLabel_randevu_al = new javax.swing.JLabel();
    //jLabel_randevu_al.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\register_1.png")); // NOI18N
    //
    
    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        if(Tckn==1){
            this.setVisible(false);
        anasayfa ana_sayfa = null;
        try {
            ana_sayfa = new anasayfa(true,isim,Tckn,doktor_kayit.d_id);
        } catch (SQLException ex) {
            Logger.getLogger(hasta_kayit.class.getName()).log(Level.SEVERE, null, ex);
        }
        ana_sayfa.setVisible(true);
        }
        else{
            this.setVisible(false);
        anasayfa ana_sayfa = null;
        try {
            ana_sayfa = new anasayfa(false,isim,Tckn,doktor_kayit.d_id);
        } catch (SQLException ex) {
            Logger.getLogger(hasta_kayit.class.getName()).log(Level.SEVERE, null, ex);
        }
        ana_sayfa.setVisible(true);
        }
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
        this.setVisible(false);
        hasta_giris h_giris = new hasta_giris();
        h_giris.setVisible(true);
    }//GEN-LAST:event_jButton_registerActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasta_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasta_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasta_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasta_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasta_kayit(isim,Tckn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_checked;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_register;
    private javax.swing.JButton jButton_restart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_hasta_adi;
    private javax.swing.JTextField jTextField_hasta_soyadi;
    private javax.swing.JTextField jTextField_hasta_tckn;
    // End of variables declaration//GEN-END:variables
}
