package sayfalar;

import Kullanicilar.hasta;
import UI_Hasta.UI_Hasta;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sql_islemleri.sql_kullanici_islemleri;
import tablolar.Tablo;

public class hasta_guncelle extends javax.swing.JFrame {

    //degiskenler
    private String DB_Kullanici = "hastane";
    public static String isim;
    public static int Tckn;
    public int temp_tckn;
    public int temp_id;

    //classlar
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    ImageIcon icon = new ImageIcon("src\\main\\java\\images\\checked.png");
    sql_kullanici_islemleri sqlKullaniciİslemleri = new sql_kullanici_islemleri(DB_Kullanici);
    Tablo HastaTablo;
    LinkedList<hasta> linkedlist_hasta = new LinkedList<>();

    /**
     * Creates new form hasta_kayit
     */
    public hasta_guncelle(String isim, int tckn) throws SQLException {
        initComponents();
        //ekrani tam ortaya ayarladik
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.isim = isim;
        this.Tckn = tckn;
        HastaTablo = new Tablo(jTable);
        try {
            sqlKullaniciİslemleri.tum_hastalari_listele();
        } catch (SQLException ex) {
            Logger.getLogger(hasta_guncelle.class.getName()).log(Level.SEVERE, null, ex);
        }
        Integer sayac = 0;
        linkedlist_hasta = sqlKullaniciİslemleri.tum_hastalari_listele();
        sayac = linkedlist_hasta.size();
        HastaTablo.TumHastalarTabloDuzenle();
        if (sayac == 0) {
            JOptionPane.showMessageDialog(this, "hastalar bulunamadi!");
        } else {
            for (int i = 0; i < sayac; i++) {

                HastaTablo.TumHastalarTabloDoldur(linkedlist_hasta.get(i));
            }
        }
        
        //jtextfieldi, jpasswordfield gibi * ile yazdirma
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_hasta_tckn = new javax.swing.JTextField();
        jTextField_hasta_adi = new javax.swing.JTextField();
        jTextField_hasta_soyadi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_restart = new javax.swing.JButton();
        jButton_checked = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        jButton_register = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_icon = new javax.swing.JLabel();
        jButton_delete = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(62, 62, 62));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(62, 62, 62));

        jTextField_hasta_tckn.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_hasta_tckn.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_hasta_tckn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_hasta_tckn.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "hasta tckn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N
        jTextField_hasta_tckn.setEnabled(false);

        jTextField_hasta_adi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_hasta_adi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_hasta_adi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_hasta_adi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "hasta adı", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N
        jTextField_hasta_adi.setEnabled(false);

        jTextField_hasta_soyadi.setBackground(new java.awt.Color(62, 62, 62));
        jTextField_hasta_soyadi.setForeground(new java.awt.Color(245, 229, 193));
        jTextField_hasta_soyadi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_hasta_soyadi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "hasta soyadi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N
        jTextField_hasta_soyadi.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 114, 43));
        jLabel1.setText("Hasta Guncelle");

        jButton_restart.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\restart.png")); // NOI18N
        jButton_restart.setEnabled(false);
        jButton_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restartActionPerformed(evt);
            }
        });

        jButton_checked.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\checked.png")); // NOI18N
        jButton_checked.setEnabled(false);
        jButton_checked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkedActionPerformed(evt);
            }
        });

        jButton_home.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\home.png")); // NOI18N
        jButton_home.setEnabled(false);
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_register.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\register.png")); // NOI18N
        jButton_register.setEnabled(false);
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        jTable.setBackground(new java.awt.Color(60, 63, 65));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 114, 43));
        jLabel2.setText("Guncellenecek ya da silinecek hastayi seciniz");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\update.png")); // NOI18N
        jLabel_icon.setEnabled(false);

        jButton_delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Korac\\Documents\\NetBeansProjects\\hastane_otomasyon_v02\\src\\main\\java\\images\\delete.png")); // NOI18N
        jButton_delete.setEnabled(false);
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(62, 62, 62));
        jPasswordField.setForeground(new java.awt.Color(245, 229, 193));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 114, 43), 2, true), "Şifre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 114, 43))); // NOI18N
        jPasswordField.setEnabled(false);
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_hasta_tckn, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_hasta_adi, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_hasta_soyadi, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_icon, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_delete)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_restart)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_home)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_register)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_checked)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_icon)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(46, 46, 46)
                .addComponent(jTextField_hasta_tckn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_hasta_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_hasta_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_checked)
                    .addComponent(jButton_restart)
                    .addComponent(jButton_home)
                    .addComponent(jButton_register)
                    .addComponent(jButton_delete))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
        this.setVisible(false);
        hasta_giris h_giris = new hasta_giris();
        h_giris.setVisible(true);
    }//GEN-LAST:event_jButton_registerActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        this.setVisible(false);
        anasayfa ana_sayfa = null;
        try {
            ana_sayfa = new anasayfa(true, isim, Tckn, doktor_kayit.d_id); //false->true yapildi
        } catch (SQLException ex) {
            Logger.getLogger(hasta_guncelle.class.getName()).log(Level.SEVERE, null, ex);
        }
        ana_sayfa.setVisible(true);
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_checkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkedActionPerformed
        // hasta nesnesi olusturuldu
        String girilenSifre = new String(jPasswordField.getPassword());
        UI_Hasta ui_hasta = new UI_Hasta(
                jTextField_hasta_tckn,
                jTextField_hasta_adi,
                jTextField_hasta_soyadi,
                jPasswordField
        );
        if (ui_hasta.bos_alan_kontrol_guncelle() /*|| ==Integer.parseInt(jTextField_hasta_id.getText())*/) {
            ui_hasta.hasta_guncelle2(temp_tckn);
            JOptionPane.showMessageDialog(this, "Hasta basariyla guncellendi :)", "Guncelleme Basarili !", JOptionPane.PLAIN_MESSAGE, icon);
            Integer sayac = 0;
            try {
                linkedlist_hasta = sqlKullaniciİslemleri.tum_hastalari_listele();
            } catch (SQLException ex) {
                
            }
        sayac = linkedlist_hasta.size();
        HastaTablo.TumHastalarTabloDuzenle();
        if (sayac == 0) {
            JOptionPane.showMessageDialog(this, "hastalar bulunamadi!");
        } else {
            for (int i = 0; i < sayac; i++) {

                HastaTablo.TumHastalarTabloDoldur(linkedlist_hasta.get(i));
            }
        }
        } else {
            JOptionPane.showMessageDialog(this, "Bos alan birakmayiniz !    ", "Uyari!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_checkedActionPerformed

    private void jButton_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restartActionPerformed
        this.jTextField_hasta_tckn.setText("");
        this.jTextField_hasta_adi.setText("");
        this.jTextField_hasta_soyadi.setText("");
        this.jPasswordField.setText("");
    }//GEN-LAST:event_jButton_restartActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        //bazi komponentler aktiflestirilecek
        jButton_checked.setEnabled(true);
        jButton_home.setEnabled(true);
        jButton_register.setEnabled(true);
        jButton_restart.setEnabled(true);
        jButton_delete.setEnabled(true);

        jTextField_hasta_adi.setEnabled(true);
        //jTextField_hasta_id.setEnabled(true);
        jTextField_hasta_soyadi.setEnabled(true);
        jPasswordField.setEnabled(true);
        jTextField_hasta_tckn.setEnabled(true);

        jLabel_icon.setEnabled(true);

        int secilen_satir = jTable.getSelectedRow();
        int tckn = (int) jTable.getValueAt(secilen_satir, 0);
        String ad = (String) jTable.getValueAt(secilen_satir, 1);
        String soyad = (String) jTable.getValueAt(secilen_satir, 2);
        String Tckn = Integer.toString(tckn);
        temp_tckn = tckn;
        jTextField_hasta_tckn.setText(Tckn);
        jTextField_hasta_adi.setText(ad);
        jTextField_hasta_soyadi.setText(soyad);
    }//GEN-LAST:event_jTableMouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // silme islemi hasta tckn alsan yeter
         // hasta nesnesi olusturuldu
        
        if (sqlKullaniciİslemleri.hasta_sil(temp_tckn)) 
            JOptionPane.showMessageDialog(this, "Hasta basariyla silindi", "Silme Basarili !", JOptionPane.PLAIN_MESSAGE, icon);
            Integer sayac = 0;
            try {
                linkedlist_hasta = sqlKullaniciİslemleri.tum_hastalari_listele();
            } catch (SQLException ex) {
                Logger.getLogger(hasta_guncelle.class.getName()).log(Level.SEVERE, null, ex);
            }
        //silindikten sonra tabloyu yenileyecek
            sayac = linkedlist_hasta.size();
        HastaTablo.TumHastalarTabloDuzenle();
        if (sayac == 0) {
            JOptionPane.showMessageDialog(this, "hastalar bulunamadi!");
        } else {
            for (int i = 0; i < sayac; i++) {

                HastaTablo.TumHastalarTabloDoldur(linkedlist_hasta.get(i));
            }
        }
         
        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasta_guncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasta_guncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasta_guncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasta_guncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new hasta_guncelle(isim, Tckn).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(hasta_guncelle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_checked;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_register;
    private javax.swing.JButton jButton_restart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField_hasta_adi;
    private javax.swing.JTextField jTextField_hasta_soyadi;
    private javax.swing.JTextField jTextField_hasta_tckn;
    // End of variables declaration//GEN-END:variables
}
